-- 전체 조회
SELECT * FROM TBL_PRODUCT;
-- 카테고리 조회
SELECT * FROM TBL_PRODUCT WHERE CATEGORY = 'B1';
-- 상품명 조회
SELECT * FROM TBL_PRODUCT WHERE PNAME LIKE '%'|| '사과' || '%';
-- 가격대 조회
SELECT * FROM TBL_PRODUCT WHERE PRICE BETWEEN 10000 AND 40000;
-- 위의 3가지 모두 적용하기
SELECT * FROM TBL_PRODUCT
WHERE CATEGORY = 'B2' AND PNAME LIKE '%'|| '사과' || '%' AND (PRICE BETWEEN 10000 AND 40000);

-- 카테고리 출력
SELECT DISTINCT CATEGORY FROM TBL_PRODUCT ORDER BY CATEGORY;
-- 카테고리 저장 테이블
CREATE TABLE TBL_CATEGORY(
	CODE CHAR(2) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL
);

SELECT * FROM TBL_CATEGORY;

INSERT INTO TBL_CATEGORY VALUES('A1','국내과일');
INSERT INTO TBL_CATEGORY VALUES('A2','수입과일');
INSERT INTO TBL_CATEGORY VALUES('B1','인스턴트');
INSERT INTO TBL_CATEGORY VALUES('B2','선물세트');
INSERT INTO TBL_CATEGORY VALUES('C1','과자류');